config/routes.rb
Rails.application.routes.draw do
  resources :involvements
  resources :nop_evidences
  resources :yes_evidences
  resources :claims
  resources :sources
  resources :jobs
  resources :people
  devise_for :users

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/source.rb
# == Schema Information
#
# Table name: sources
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :string
#  person_id   :integer
#  released_at :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  url         :string
#

class Source < ApplicationRecord
  belongs_to :person
  has_many :yes_evidences
  has_many :nop_evidences
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  authorize_resource
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.order(released_at: :desc)
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:title, :body, :person_id, :released_at, :url)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
  def source_link_to_url source
    return nil if source.nil? || source.url.blank?

    link_to(source.url, "//#{source.url}", target: '_blank')
  end
end

app/views/sources/_form.html.erb
<%= form_with(model: source, local: true) do |form| %>
  <% if source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :body, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :person_id, 'Claimed by', class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.select :person_id, Person.all.pluck(:name, :id), {}, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group position-relative row">
    <%= form.label :released_at, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.date_field :released_at, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :url, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class="text-center">
    <%= form.submit class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/sources/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <% if can? :manage, Source %>
        <th>#</th>
      <% end %>
      <th></th>
      <th>Person</th>
      <th>Released at</th>
      <th>Url</th>
      <% if can? :manage, Source %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% sources.each do |source| %>
      <tr>
        <% if can? :manage, Source %>
          <td><%= link_to source.id, source %></td>
        <% end %>
        <td><%= link_to source.title, source %></td>
        <td><%= link_to source.person.name, source.person %></td>
        <td><%=l source.released_at, format: :short %></td>
        <td><%= source_link_to_url source %></td>
        <% if can? :manage, Source %>
          <td>
            <%= link_to 'E', edit_source_path(source) if can? :manage, Source %>
            <%= link_to 'D', source, method: :delete, data: { confirm: 'Are you sure?' } if can? :manage, Source %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sources/edit.html.erb
<div class="container">
  <h1 class="text-center">Editing Source</h1>

  <%= render 'form', source: @source %>

  <%= link_to 'Show', @source %> |
  <%= link_to 'Back', sources_path %>
</div>

app/views/sources/index.html.erb
<div class="container">
  <div class="row text-center my-4">
    <div class="col-4">
      <h2><%= link_to 'Persone', people_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Affermazioni', claims_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Fonti', sources_path, class: 'btn btn-secondary btn-lg' %></h2>
    </div>
  </div>

  <%= link_to 'Nuova fonte', new_source_path if can? :manage, Source %>

  <%= render 'table', sources: @sources %>
</div>

app/views/sources/new.html.erb
<div class="container">
  <h1 class="text-center">New Source</h1>

  <%= render 'form', source: @source %>

  <%= link_to 'Back', sources_path %>
</div>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @source.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @source.body %>
</p>

<p>
  <strong>Person:</strong>
  <%= link_to @source.person.name, @source.person %>
</p>

<p>
  <strong>Released at:</strong>
  <%= @source.released_at %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to "EXTERNAL URL: #{@source.url}", "//#{@source.url}", target: '_blank' %>
</p>

<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>