config/routes.rb
Rails.application.routes.draw do
  resources :involvements
  resources :nop_evidences
  resources :yes_evidences
  resources :claims
  resources :sources
  resources :jobs
  resources :people
  devise_for :users

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  name       :string
#  born_at    :datetime
#  dead_at    :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Person < ApplicationRecord
  has_many :jobs
  accepts_nested_attributes_for :jobs, allow_destroy: true
  has_many :sources
  has_many :claims
  has_many :involvements

  validates :name, presence: true
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  authorize_resource
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.jobs.build
  end

  # GET /people/1/edit
  def edit
    @person.jobs.build
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :born_at, :dead_at, jobs_attributes: [:id, :person_id, :name, :started_at, :ended_at, :_destroy])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
  def person_name_and_dates person
    return nil if person.nil?

    [person.name, person_dates(person)].compact.join(' ')
  end

  def person_dates person
    return nil if person.nil?

    if person.born_at.present? && person.dead_at.present?
      "(#{l person.born_at, format: :short} - #{l person.dead_at, format: :short})"
    elsif person.born_at.present?
      "(#{l person.born_at, format: :short}, #{time_ago_in_words person.born_at})"
    elsif person.dead_at.present?
      "(? - #{l person.dead_at, format: :short})"
    end
  end
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group position-relative row">
    <%= form.label :born_at, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.date_field :born_at, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group position-relative row">
    <%= form.label :dead_at, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.date_field :dead_at, class: 'col-sm-8 form-control' %>
    </div>
  </div>

  <div data-controller="nested-form">
    <h2 class="text-sm-right">Jobs</h2>

    <%= form.fields_for :jobs, person.jobs do |ff| %>
      <div data-target="nested-form.object">
        <div class="form-group row">
          <label class="text-sm-right col-sm-4 col-form-label">Name</label>
          <div class="col-sm-8">
            <%= ff.text_field :name, class: 'form-control' %>
          </div>

          <%= ff.label :started_at, class: "text-sm-right col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= ff.date_field :started_at, class: 'form-control' %>
          </div>

          <%= ff.label :ended_at, class: "text-sm-right col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= ff.date_field :ended_at, class: 'form-control' %>
          </div>

          <div class="col-sm-12 align-self-center text-sm-right pt-1">
            <button type="button" class="btn btn-link text-danger" data-action="nested-form#remove" data-original-title="Remove" data-toggle="tooltip">
              <%= ff.label :_destroy, class: 'mb-0' do %>
                <%= ff.check_box :_destroy, class: 'd-none' %>
                <i class="fas fa-trash"></i> Remove
              <% end %>
            </button>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group text-sm-right">
      <button type="button" class="btn btn-primary btn-sm" data-action="nested-form#add">
        <i class="fal fa-plus-circle"></i> Add new Job
      </button>
    </div>
  </div>


  <div class="text-center">
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/people/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <% if can? :manage, Person %>
        <th>#</th>
      <% end %>
      <th></th>
      <th>Last job</th>
      <th>Sources</th>
      <th>Claims</th>
      <th>Involvements</th>
      <% if can? :manage, Person %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% people.each do |person| %>
      <tr>
        <% if can? :manage, Person %>
          <td><%= link_to person.id, person %></td>
        <% end %>
        <td><%= link_to person_name_and_dates(person), person %></td>
        <td><%= job_name_and_dates person.jobs.current_or_last %></td>
        <td><%= person.sources.count %></td>
        <td><%= person.claims.count %></td>
        <td><%= person.involvements.count %></td>
        <% if can? :manage, Person %>
          <td>
            <%= link_to 'E', edit_person_path(person) %>
            <%= link_to 'D', person, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/edit.html.erb
<div class="container">
  <h1 class="text-center">Editing Person</h1>

  <%= render 'form', person: @person %>

  <%= link_to 'Show', @person %> |
  <%= link_to 'Back', people_path %>
</div>

app/views/people/index.html.erb
<div class="container">
  <div class="row text-center my-4">
    <div class="col-4">
      <h2><%= link_to 'Persone', people_path, class: 'btn btn-secondary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Affermazioni', claims_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Fonti', sources_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
  </div>

  <%= link_to 'Nuova persona', new_person_path if can? :manage, Person %>

  <%= render 'table', people: @people %>
</div>

app/views/people/new.html.erb
<div class="container">
  <h1 class="text-center">New Person</h1>

  <%= render 'form', person: @person %>

  <%= link_to 'Back', people_path %>
</div>

app/views/people/show.html.erb
<div class="container">
  <div class="row text-center my-4">
    <div class="col-4">
      <h2><%= link_to 'Persone', people_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Affermazioni', claims_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Fonti', sources_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
  </div>

  <h1><%= person_name_and_dates @person %></h1>

  <h2>Occupazioni</h2>
  <%= render 'jobs/table', jobs: @person.jobs %>

  <h2>Fonti di cui è autore</h2>
  <%= render 'sources/table', sources: @person.sources %>

  <h2>Affermazioni fatte</h2>
  <%= render 'claims/table', claims: @person.claims %>

  <h2>Affermazioni che lo coinvolgono</h2>
  <%= render 'involvements/table', involvements: @person.involvements %>

  <% if can? :manage, Person %>
    <%= link_to 'Edit', edit_person_path(@person) %><br/>
  <% end %>
</div>