config/routes.rb
Rails.application.routes.draw do
  resources :involvements
  resources :nop_evidences
  resources :yes_evidences
  resources :claims
  resources :sources
  resources :jobs
  resources :people
  devise_for :users

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/claim.rb
# == Schema Information
#
# Table name: claims
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :string
#  person_id   :integer
#  claimed_at  :datetime
#  happened_at :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Claim < ApplicationRecord
  belongs_to :person
  has_many :yes_evidences
  accepts_nested_attributes_for :yes_evidences, allow_destroy: true
  has_many :nop_evidences
  accepts_nested_attributes_for :nop_evidences, allow_destroy: true
  has_many :involvements
  accepts_nested_attributes_for :involvements, allow_destroy: true

  validates :title, presence: true
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  authorize_resource
  before_action :set_claim, only: [:show, :edit, :update, :destroy]

  # GET /claims
  # GET /claims.json
  def index
    @claims = Claim.all
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
    @claim.involvements.build
    @claim.nop_evidences.build
    @claim.yes_evidences.build
  end

  # GET /claims/1/edit
  def edit
    @claim.involvements.build
    @claim.nop_evidences.build
    @claim.yes_evidences.build
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = Claim.new(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      nop_evidences_attributes = [:id, :claim_id, :source_id, :_destroy]
      yes_evidences_attributes = [:id, :claim_id, :source_id, :_destroy]
      involvements_attributes = [:id, :claim_id, :person_id, :_destroy]
      params.require(:claim).permit(
        :title, :body, :person_id, :claimed_at, :happened_at,
        involvements_attributes: involvements_attributes,
        nop_evidences_attributes: nop_evidences_attributes,
        yes_evidences_attributes: yes_evidences_attributes
      )
    end
end

app/helpers/claims_helper.rb
module ClaimsHelper
  def claim_title_and_dates claim
    return nil if claim.nil?

    [claim.title, claim_dates(claim)].compact.join(' ')
  end

  def claim_dates claim
    return nil if claim.nil?

    if claim.happened_at.present? && claim.claimed_at.present?
      "(Happened: #{l claim.happened_at, format: :short}; claimed: #{l claim.claimed_at, format: :short})"
    elsif claim.happened_at.present?
      "(Happened: #{l claim.happened_at, format: :short})"
    elsif claim.claimed_at.present?
      "(Claimed: #{l claim.claimed_at, format: :short})"
    end
  end
end

app/views/claims/_form.html.erb
<%= form_with model: claim, local: true, data: { controller: 'form' } do |form| %>
  <% if claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

      <ul>
      <% claim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :body, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :person_id, 'Claimed by', class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.select :person_id, Person.all.pluck(:name, :id), {}, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group position-relative row">
    <%= form.label :claimed_at, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.date_field :claimed_at, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group position-relative row">
    <%= form.label :happened_at, class: "text-sm-right col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= form.date_field :happened_at, class: 'form-control' %>
    </div>
  </div>

  <div data-controller="nested-form">
    <h2 class="text-sm-right">Involvements</h2>
    <%= form.fields_for :involvements, claim.involvements do |ff| %>
      <div data-target="nested-form.object">
        <div class="form-group row">
          <label class="text-sm-right col-sm-4 col-form-label">Person</label>
          <div class="col-sm-6">
            <%= ff.select :person_id, Person.all.pluck(:name, :id), {}, class: 'form-control' %>
          </div>

          <div class="col-sm-2 align-self-center text-sm-right">
            <button type="button" class="btn btn-link text-danger" data-action="nested-form#remove" data-original-title="Remove" data-toggle="tooltip">
              <%= ff.label :_destroy, class: 'mb-0' do %>
                <%= ff.check_box :_destroy, class: 'd-none' %>
                <i class="fas fa-trash"></i> Remove
              <% end %>
            </button>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group text-sm-right">
      <button type="button" class="btn btn-primary btn-sm" data-action="nested-form#add">
        <i class="fal fa-plus-circle"></i> Add new involvment
      </button>
    </div>
  </div>

  <div data-controller="nested-form">
    <h2 class="text-sm-right">Yes Evidences</h2>
    <%= form.fields_for :yes_evidences, claim.yes_evidences do |ff| %>
      <div data-target="nested-form.object">
        <div class="form-group row">
          <label class="text-sm-right col-sm-4 col-form-label">Source</label>
          <div class="col-sm-6">
            <%= ff.select :source_id, Source.all.pluck(:title, :id), {}, class: 'form-control' %>
          </div>

          <div class="col-sm-2 align-self-center text-sm-right">
            <button type="button" class="btn btn-link text-danger" data-action="nested-form#remove" data-original-title="Remove" data-toggle="tooltip">
              <%= ff.label :_destroy, class: 'mb-0' do %>
                <%= ff.check_box :_destroy, class: 'd-none' %>
                <i class="fas fa-trash"></i> Remove
              <% end %>
            </button>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group text-sm-right">
      <button type="button" class="btn btn-primary btn-sm" data-action="nested-form#add">
        <i class="fal fa-plus-circle"></i> Add new yes evidence
      </button>
    </div>
  </div>

  <div data-controller="nested-form">
    <h2 class="text-sm-right">Nope Evidences</h2>
    <%= form.fields_for :nop_evidences, claim.nop_evidences do |ff| %>
      <div data-target="nested-form.object">
        <div class="form-group row">
          <label class="text-sm-right col-sm-4 col-form-label">Source</label>
          <div class="col-sm-6">
            <%= ff.select :source_id, Source.all.pluck(:title, :id), {}, class: 'form-control' %>
          </div>

          <div class="col-sm-2 align-self-center text-sm-right">
            <button type="button" class="btn btn-link text-danger" data-action="nested-form#remove" data-original-title="Remove" data-toggle="tooltip">
              <%= ff.label :_destroy, class: 'mb-0' do %>
                <%= ff.check_box :_destroy, class: 'd-none' %>
                <i class="fas fa-trash"></i> Remove
              <% end %>
            </button>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group text-sm-right">
      <button type="button" class="btn btn-primary btn-sm" data-action="nested-form#add">
        <i class="fal fa-plus-circle"></i> Add new nope evidence
      </button>
    </div>
  </div>

  <div class="text-center">
    <%= form.submit class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/claims/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <% if can? :manage, Claim %>
        <th>#</th>
      <% end %>
      <th></th>
      <th>Person</th>
      <th>Happened at</th>
      <th>Claimed at</th>
      <th>Evidences</th>
      <% if can? :manage, Claim %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% claims.each do |claim| %>
      <tr>
        <% if can? :manage, Claim %>
          <td><%= link_to claim.id, claim %></td>
        <% end %>
        <td><%= claim.title %></td>
        <td><%= link_to claim.person.name, claim.person %></td>
        <td><%=l(claim.happened_at, format: :short) if claim.happened_at.present? %></td>
        <td><%=l(claim.claimed_at, format: :short) if claim.claimed_at.present? %></td>
        <td>
          Yes: <%= claim.yes_evidences.count %>
          Nop: <%= claim.nop_evidences.count %>
        </td>
        <% if can? :manage, Claim %>
          <td>
            <%= link_to 'E', edit_claim_path(claim) %>
            <%= link_to 'D', claim, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/claims/edit.html.erb
<div class="container">
  <h1>Editing Claim</h1>

  <%= render 'form', claim: @claim %>

  <%= link_to 'Show', @claim %> |
  <%= link_to 'Back', claims_path %>
</div>

app/views/claims/index.html.erb
<div class="container">
  <div class="row text-center my-4">
    <div class="col-4">
      <h2><%= link_to 'Persone', people_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Affermazioni', claims_path, class: 'btn btn-secondary btn-lg' %></h2>
    </div>
    <div class="col-4">
      <h2><%= link_to 'Fonti', sources_path, class: 'btn btn-primary btn-lg' %></h2>
    </div>
  </div>

  <%= link_to 'Nuova affermazione', new_claim_path if can? :create, Claim %>

  <%= render 'table', claims: @claims %>
</div>

app/views/claims/new.html.erb
<div class="container">
  <h1>New Claim</h1>

  <%= render 'form', claim: @claim %>

  <%= link_to 'Back', claims_path %>
</div>

app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @claim.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @claim.body %>
</p>

<p>
  <strong>Person:</strong>
  <%= link_to @claim.person.name, @claim.person %>
</p>

<p>
  <strong>Claimed at:</strong>
  <%=l @claim.claimed_at rescue nil %>
</p>

<p>
  <strong>Happened at:</strong>
  <%=l @claim.happened_at rescue nil %>
</p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>